name: bento_clone
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.12.0
  get_it: ^9.2.0
  google_fonts: ^8.0.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/bubbles.png
    - assets/Sid Gen.png
    - assets/SiD.png
    - assets/git_graph.png
    - assets/1635723301936.jpg
    - assets/data/popular_links.json
